### ISSUE TITLE
:farmer: Homebrew warning: Policy CMP0177 not set

### ISSUE THREAD

**Issue by Crola1702** [gazebosim/gz-plugin#156]
## Environment
* OS Version: MacOS (all versions)
* Source build (all versions)

## Description
* Expected behavior: Build should pass
* Actual behavior: There are some warnings popping up in homebrew CI builds

## Output

Reference builds:
* https://build.osrfoundation.org/job/gz_plugin-ci-main-homebrew-amd64/96/
* https://build.osrfoundation.org/job/gz_plugin-ci-gz-plugin3-homebrew-amd64/25/
* https://build.osrfoundation.org/job/gz_plugin-ci-gz-plugin2-homebrew-amd64/95/
* https://build.osrfoundation.org/job/gz_plugin-ci-ign-plugin1-homebrew-amd64/92/

```
CMake Warning (dev) at /usr/local/share/cmake/gz-cmake4/cmake4/GzInstallAllHeaders.cmake:182 (install):
  Policy CMP0177 is not set: install() DESTINATION paths are normalized.  Run
  "cmake --help-policy CMP0177" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.
Call Stack (most recent call first):
  core/include/gz/plugin/CMakeLists.txt:1 (gz_install_all_headers)
This warning is for project developers.  Use -Wno-dev to suppress it.
```

Also, older versions of plugin show another warning:

```
CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 3.10 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
  to tell CMake that the project requires at least <min> but has been updated
  to work with policies introduced by <max> or earlier.
```

**Comment by azeey** [comment]
I think this is a duplicate of https://github.com/gazebosim/gz-cmake/issues/461

**Comment by Crola1702** [comment]
> I think this is a duplicate of https://github.com/gazebosim/gz-cmake/issues/461

Closing in favor of https://github.com/gazebosim/gz-cmake/issues/461
