### ISSUE TITLE
Add standalone executable for ign-plugin-info command

### ISSUE THREAD

**Issue by scpeters** [gazebosim/gz-plugin#54]
We updated the ign-transport `ign topic` and `ign service` commands to use standalone executables in https://github.com/ignitionrobotics/ign-transport/pull/216. We should do the same for the `ign plugin --info` command defined in the loader component:

* https://github.com/ignitionrobotics/ign-plugin/blob/ign-plugin1/loader/src/cmd/cmdplugin.rb.in

similar to https://github.com/ignitionrobotics/ign-transport/issues/247

**Comment by ahcorde** [comment]
PR https://github.com/ignitionrobotics/ign-plugin/pull/65

**Comment by ahcorde** [comment]
This feature is already merged in `ign-plugin2`
